var x = 2;
var y = 5;
var z = 8;

var t = '2';

var u = t -y;

// console.log(x+y);
// console.log(x+t);

/* console.log(z  - t);
console.log(t  - y);

console.log(typeof u, u);

console.log(z / t); */


// console.log(typeof (5/2));


/* var a = 5;
var b = 0;

// console.log(a/b);

// console.log(typeof Infinity);
 
//https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence
var c = 100+50*3

console.log(c); */


//Increment decrement
// var a = 10;

// console.log(a++);
// console.log(a);

// var b = 5;
// console.log(b);
// console.log(++b);
// console.log(++b);


// var c = 8;

// // console.log(c--);
// // console.log(c);

// // var d = c++
// // var d = ++c

// // console.log({d},{c});

// console.log(c++ + ++c);

// var input = +prompt("Enter age");

// console.log(input, typeof input);

// var c = '8';

// console.log(-c);

// var a = 4;
// var b = '4';

// // var c = a === b;

// // console.log(a == b);
// // console.log(c);


// console.log(a !== b);

// var a = 'a';
// var b = 'A';

// console.log(a.charCodeAt());
// console.log(b.charCodeAt());
// console.log('A' > 'a');
// console.log(50  97);


// console.log('FullStack' <= 'FullSt');


// var a = (2 || 3)
// var a = (0 || 3)

// console.log(a);

// var b = (0 && false)
// var b = (2 && 3)
// console.log(b);

// console.log(null && NaN);

// var capitalLetter = false;
// var symbol = true;
// var passLength = true;

// var result = capitalLetter && (symbol || passLength);

// console.log(!result || 'Try again');

// var a;
// console.log(a);

// console.log(a ?? 'Null veya undefined');

// var b = null;

// console.log(b ?? a);

var c = 1;

console.log(c ?? 'Null veya undefined');
